name: Run pipeline

on:
  push:
    branches:
      - main
      - lab3

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: run lab2
        run: |
          chmod +x deliverables/lab02/lab2.sh
          ./deliverables/lab02/lab2.sh
